DROP TABLE IF EXISTS todo;
CREATE TABLE todo (
    id INT AUTO_INCREMENT PRIMARY KEY,
    task VARCHAR(255) NOT NULL,
    completed TINYINT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    due_date DATETIME NULL,
    completed_at TIMESTAMP NULL
);
